name: ScratchTools

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Well, welcome to the ScratchTools Issues section! We are VERY glad to have you with us! Thanks for contributing! Remember, you get credit based on how much you contribute!'
        pr-message: 'Well, welcome to the ScratchTools Pull Requests section! We are VERY glad to have you with us! Thanks for contributing! Remember, you get credit based on how much you contribute!'
